### ISSUE TITLE
Unable to sleep

### ISSUE THREAD

**Issue by Lordbaane** [MC-U-Team/Overworld-Mirror#1]
Not sure if this an issue from another mod, but when trying to sleep at night it doesn't switch to day in the mirrorworld.

**Comment by MrTroble** [comment]
Hello @Lordbaane we are looking into this issue. Thanks for reporting! :)

**Comment by HyCraftHD** [comment]
Well i can't reproduce this behavior. The time in the overworld mirror is the same as in the overworld. But you can sleep in both worlds and the time will update as expected. Which other mods for sleeping do you have installed?

**Comment by Lordbaane** [comment]
That is the strangest thing. None of the mods are designed for sleep. I'm going to see if I can reproduce it, but I'll be honest it was weird. I could go to sleep, but I wake right away. Lemme try it again. Maybe it just was a glitch for that world.

**Comment by Lordbaane** [comment]
Okay, so I dropped some mods, started up a new world and still have the same issue. I go to sleep, but when I awake it is still dark. I try a fresh start with only your mod and two others then begin to add several at a time to see when it becomes an issue.

**Comment by Lordbaane** [comment]
Okay, I've stripped it down just to the mod itself and I still have an issue:
1. Was in creative when i tried 
2. Tried in survival same
3. Did not sleep in the overworld first before trying
4. Results the same
5. Deleted config files except for forge
Using Forge 2765, no other mods or resource packs. Not sure what else to do.

**Comment by MrTroble** [comment]
Hello again @Lordbaane !

Thanks for the excessive testing! I will take some time later on too look into this!
It could be that I need more information (on your environment) later but I hope I don't need them!

Thanks again!
~MrTroble

**Comment by Lordbaane** [comment]
Update:
So I added a sleeping mod  called Sleeping Overhaul that modifies the tick rate and it worked. I also tested from the beginning for your mods and the results were the same just in case something was changed during your updates. I've also updated to 2768 for Forge as well during these tests. Hopefully this helps.

**Comment by HyCraftHD** [comment]
Hello, thank you very much for your help. I now can reproduce the problem and try to fix it soon.

Greetings, Johannes

________________________________
Von: Kevin <notifications@github.com>
Gesendet: Donnerstag, 4. Oktober 2018 19:01
An: MC-U-Team/Overworld-Mirror
Cc: Johannes; Assign
Betreff: Re: [MC-U-Team/Overworld-Mirror] Unable to sleep (#1)


Update:
So I added a sleeping mod called Sleeping Overhaul that modifies the tick rate and it worked. I also tested from the beginning for your mods and the results were the same just in case something was changed during your updates. I've also updated to 2768 for Forge as well during these tests. Hopefully this helps.

**Comment by HyCraftHD** [comment]
The fix is in build: 1.0.0.5, which can be downloaded at curseforge (when approved) or here: https://repo.u-team.info/info/u-team/overworld_mirror-1.12.2/1.0.0.5-SNAPSHOT/overworld_mirror-1.12.2-1.0.0.5-20181017.113515-1.jar
