### ISSUE TITLE
[1.12.2] Crashes with Biomes O' Plenty world type

### ISSUE THREAD

**Issue by theTARDISisme** [MC-U-Team/Overworld-Mirror#10]
**Describe the bug**

Minecraft crashes upon opening world when overworld mirror is set to BIOMESOP world type. Honestly not sure if it's an issue with Overworld Mirror or Biomes O' Plenty. It's also difficult being an older version, it's possible that the issue has been fixed for other Minecraft versions, but sadly a lot of popular mods are on 1.12.2 still.

This is what I changed in the config:
`# The worldtype of the mirrored world`
`S:"World Type"=BIOMESOP`

**To Reproduce**
1. Install Biomes O' Plenty and Overworld Mirror (including coremods)
2. Set the "World Type" to BIOMESOP
3. Create a world

**Expected behavior**
It should not crash but rather allow the mirrored world to be a Biomes O' Plenty world. I want the main overworld to be a normal world type.
(I actually wanted this mod because I created a world and played some not realizing that Biomes O' Plenty had a custom world type and thought this could be a way to use it without starting over my world.)

**Screenshots**

**Versions**
- Mod version: 1.2.1.10
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2854
- UTeamCore version: 2.2.5.147

**Log (if crash occures)**
https://pastebin.com/yGjjeSiz

**Comment by HyCraftHD** [comment]
Biomes O Plenty is not supported for the world type of the overworld mirror world unfortunately.
I'm currently updating this mod to 1.16.5, so it should work there probably
