### ISSUE TITLE
Dimension ID clashes with other mods

### ISSUE THREAD

**Issue by jaz000** [MC-U-Team/Overworld-Mirror#2]
It would be better to set the dimension ID in the config file rather than just grab the next free one.
Currently this clashes with Applied Energistics 2 mod which tries to register dimension ID 2 after Overworld Mirror

**Comment by HyCraftHD** [comment]
Well its the normal way to register dimensions. AE2 should change their static behaviour. But i'll provide a config option in the next release.

**Comment by jaz000** [comment]
thanks, that's probably reasonable, pretty much any mod with extra dimensions lets you change it somehow (pack I'm putting together currently has 57 dimensions!)
However, I have managed to change it for AE2 - for some reason I missed it first time.

it's in the config file AppliedEnergistics2.cfg as:
I:storageDimensionID=2

change this number to something else, e.g.
I:storageDimensionID=4

Then Overworld Mirror can use ID 2 :-)

**Comment by HyCraftHD** [comment]
This should now be fixed
