### ISSUE TITLE
Portal requirements

### ISSUE THREAD

**Issue by cjser** [MC-U-Team/Overworld-Mirror#3]
I try to open the open in several times and ways it never worked. Its there any special requirement?

**Comment by HyCraftHD** [comment]
Sorry, is forgot to update the curseforge page. To create the portal you need a 5x5 frame of stonebricks and in the middle 3x3 flowers. And then sneek right click with bone meal.

**Comment by HyCraftHD** [comment]
Or do you mean loading the mod? If then you need u-team-core to be installed: https://minecraft.curseforge.com/projects/u-team-core

**Comment by HyCraftHD** [comment]
Closed cause no response
