### ISSUE TITLE
[1.15.2] Portal not formed

### ISSUE THREAD

**Issue by Yamza** [MC-U-Team/Overworld-Mirror#5]
**Describe the bug**
When changing the generation settings for the dimension, if you set the surface height to not be 63, a portal will not form and going into the dimension can cause the player to become trapped under the world.

**To Reproduce**
1. Use this configuration setting https://hatebin.com/onljuivywn
2. Go to the dimension
3. A portal will not be formed and you will spawn weirdly.

**Expected behavior**
A portal to be spawned with the player in it.

**Versions**
- Mod version: overworld_mirror-1.15.2-1.3.0.12.jar
- Minecraft version: 1.15.2
- Forge version: 31.1.18
- UTeamCore version: u_team_core-1.15.2-2.10.6.155.jar

**Comment by HyCraftHD** [comment]
Should be fixed with #7
