### ISSUE TITLE
[M1.20.1] Dedicated server crash when entering mirror dim

### ISSUE THREAD

**Issue by ProsperCraft** [MC-U-Team/Overworld-Mirror#59]
### Bug description and reproduction steps

Install TownCraft for 1.20.1
Not sure if it is a sidedness issue or not, testing that now.
Go to mirror dim, crash every time you log in to server.

### Log files and Screenshots

Crash report - https://gist.github.com/ProsperCraft/4cccc85b280073c361256a31b13e033b

### Used minecraft version

1.20.x

### Used forge or fabric version

forge-1.20.1-47.1.1

### Used mod version

overworld_mirror-forge-1.20.1-1.7.0.23

**Comment by jimmon89** [comment]
NOTE: The user who encountered the dedicated server crash here

the crash didn't happen the first time upon entering the mirror dimension, it happened when i was using the leap spell from [Ars Nouveau](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau) to quickly traverse the area, and went to land near a worldgen structure (A chocobo stable from [Chocobo Knights of the Crafting Table](https://www.curseforge.com/minecraft/mc-mods/chocobo-knights-of-the-crafting-table)), not sure if it's relevent, but i'm providing it regardless
but after the initial server crash, every subsequent time i tried to log in, the server crashed again

**Comment by ProsperCraft** [comment]
Better Jukebox is not designed for sidnedness.  Removed.
