### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by foxanthony1** [MC-U-Team/Overworld-Mirror#6]
I don't see a config file in the config folder

**Versions**
- Mod version: overworld_mirror-1.15.2-1.3.0.12.jar
- Minecraft version: 1.15.2
- Forge version: forge-1.15.2-31.1.18
- UTeamCore version: u_team_core-1.15.2-2.10.5.154

**Comment by HyCraftHD** [comment]
Its in the world configuration folder. Can be packed in the default configuration folder for modpacks.

**Comment by foxanthony1** [comment]
I don't know where the "world" configuration folder is. I'm running Linux.

**Comment by HyCraftHD** [comment]
In the world. Linux has nothing to do with that.
Its the default way forge handles world only configuration files

**Comment by foxanthony1** [comment]
You mean in the Saves folder?

**Comment by HyCraftHD** [comment]
Depends if its the client or the server. Where the world is saved. migt be ~minecraft/saves/WorldXYZ/config or ~server/world/serverconfig

**Comment by foxanthony1** [comment]
Okay. There's still no file in there.

**Comment by HyCraftHD** [comment]
Have you started the world / server? Its only generated after that.

**Comment by foxanthony1** [comment]
Yes, I see the folders /overworld/dimension/data, but there's no file in the /data folder

**Comment by HyCraftHD** [comment]
Thats the wrong folder. That saves internal data.
The config is in the world under serverconfig/overworldmirror-server.toml
![grafik](https://user-images.githubusercontent.com/7681220/76164392-e6751e80-614e-11ea-80e2-a4ee936cf750.png)

**Comment by foxanthony1** [comment]
Okay, found it.

So now I can move it to .minecraft/config and tweak it to my heart's desire?

**Comment by HyCraftHD** [comment]
No. It stays there. Its per world. It can be packed in the defaultconfig folder for modpacks (and will be copied on startup to the world/serverconfig folder. If you change somethings in the world config you need to delete the overworld mirror directory in the world so the new world settings will be generated.

**Comment by foxanthony1** [comment]
Right. All I care about is making modpacks. I should have made that clear. Thanks.

Could you put the file in the usual config folder so us modpack devs will find it where we expect it to be?

**Comment by HyCraftHD** [comment]
No its the new FORGE config system and I will use that. Please adapt to new mechanics.
It also does not make any sense that it is in the common config directory because the config there can be diffrent for each world.

**Comment by HyCraftHD** [comment]
Duplicate of #4 .
