### ISSUE TITLE
[Request] Same Size as overworld!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MC-U-Team/Overworld-Mirror#8]
Pretty self-explanatory I want the mirror to be a mirror. No limits in mirror world that the over worlds would not have. Also, please back port to 1.12.2 since pixelmon is still there.

**Comment by HyCraftHD** [comment]
?
So what is your request. What limits??
Also 1.12.2 is available.

**Comment by P3rf3ctXZer0** [comment]
It says on website that "Overworld Mirror is almost the same as the overworld but with less chunke size"

![image](https://user-images.githubusercontent.com/10351221/86412005-b1ec1c00-bc83-11ea-8a40-410ce49d8153.png)

I want it to have the same chunks limit as the real overworld.

**Comment by HyCraftHD** [comment]
Well that info is outdated. Curseforge is the better source for information right now.
Thanks for reminding me. Need to update the website eventually.

**Comment by P3rf3ctXZer0** [comment]
No problem also AWESOME this mod is the bees knees :D
