### ISSUE TITLE
[1.15.2] No config file?

### ISSUE THREAD

**Issue by ghost** [MC-U-Team/Overworld-Mirror#9]
**Describe the bug**
I downloaded this mod, and I want to get an exact replica of the overworld which you can change in the so called config file, but I can't find it!

**Expected behavior**
Expected there to be a config file

**Versions**
- Mod version: 1.15.2
- Minecraft version: 1.15.2
- Forge version: Latest
- UTeamCore version: 1.15.2

**Comment by HyCraftHD** [comment]
See here: https://github.com/MC-U-Team/Overworld-Mirror/issues/6
The config file is in the world
